services:
  auth_database:
    container_name: auth_db_container
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jobber-authentication
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  user_database:
    container_name: user_db_container
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: jobber-users
    volumes:
      - ./docker-volumes/mongodb_data:/data/db
  
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user # Default username
      RABBITMQ_DEFAULT_PASS: password # Default password
    ports:
      - '5672:5672' #AMQP
      - '15672:15672' #Dashboard
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
 
 

 