services:
  auth_database:
    container_name: auth_db_container
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authentication
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
 
 

 