services:
  auth_database:
    container_name: auth_db_container
    image: mysql:latest
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authentication
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user # Default username
      RABBITMQ_DEFAULT_PASS: password # Default password
    ports:
      - '5672:5672' #AMQP
      - '15672:15672' #Dashboard
 
 

 